### ISSUE TITLE
Remove field/row element need to be tabindexed

### ISSUE THREAD

**Issue by klngwll** [libris/kitin#143]

**Comment by oBlissing** [comment]
If you add a href attr to an <a> tag it will be included in the tabindex order automatically.

**Comment by oBlissing** [comment]
When an element which is focused is removed from the DOM the tabpointer will be reset, causing it to lose track of where you were. Unsure of how to handle this.

**Comment by niklasl** [comment]
We might be able to move to next item before removal. Either using a tab-pointer API (is there one?), or by finding next focusable item and calling it's `focus()`.
