### ISSUE TITLE
Validate against possible organisation ID's

### ISSUE THREAD

**Issue by klngwll** [libris/kitin#148]
Encountered bug where I was logged in as sigel NONE.

**Comment by sweco-semhul** [comment]
Should whelk or klient check if sigel in holdings record matches return from oauth verify token request?
Otherwise there is a possible risk than any logged in user can alter sigels in holdings records and write to whelk.
Could this also be a risk for bib records?

**Comment by sweco-semhul** [comment]
Solved in back-end
