### ISSUE TITLE
Footer (information etc)

### ISSUE THREAD

**Issue by klngwll** [libris/kitin#154]
Do we need an extended footer with contact information (support mail phone) information about cookies etc or should this be a link to a separate page?

**Comment by oBlissing** [comment]
Informations about cookies added with cad16106cd3a37f6afe22191a676f28c68aa3bbb

**Comment by oBlissing** [comment]
Contact modal has been removed. We'll just link to Kundo, and put detailed contact information somewhere at the Kundo page.
