### ISSUE TITLE
Add info message if the form has unsaved changes when user leaves page

### ISSUE THREAD

**Issue by sweco-semhul** [libris/kitin#172]
If dirty flag is set and the user tries to leave the page, show a pop up to remind the user to save the changes.

**Comment by oBlissing** [comment]
This is done for holdings.
Edit page and auth should also be tied to this event later on. Their flags should be rewired to work the same way first.

**Comment by oBlissing** [comment]
Done for edit record form. Still an issue with IE9 (#216)
