### ISSUE TITLE
Sync properties on holding with it's related bibliographic data

### ISSUE THREAD

**Issue by klngwll** [libris/kitin#181]
From Leader/00-23:

TODO: explain this in concise steps
	(06) XXXXXnx  a22XXXXX1n 4500	[<-- då beståndet avser monografisk resurs med bib-leader/07: a,c,d,m]
	(06) XXXXXny  a22XXXXX1n 4500	[<-- då beståndet avser fortlöpande resurs med bib-leader/07: b,i,s]
	X = maskinellt skapade värden enligt ISO2709
	n (leader/05) = ny beståndspost; ändras automatiskt till c vid uppdatering
	_ (leader/07) = statistik-/produktkod med alternativa värden o (undertrycks i nyförvärvslista) resp. r (retrospektiv katalogisering)) - alternativen behövs ej på nivån Basic-Basic

**Comment by sweco-semhul** [comment]
There is a pending solution for this in the back-end layer.

**Comment by niklasl** [comment]
See libris/librisxl#103
