### ISSUE TITLE
Repeatable fields should have one field at init

### ISSUE THREAD

**Issue by oBlissing** [libris/kitin#255]

**Comment by sweco-semhul** [comment]
Add configurable attribute and/or default logic to run doCreate(),
Typically add more logic to the model watcher  https://github.com/libris/kitin/blob/develop/static/js/directives/KitinTable.js#L126

**Comment by oBlissing** [comment]
Deactivated adding empty rows on save instead. The input form is more consistent and properly reflecting the data if we don't add empty rows to the table when there is no data.
