### ISSUE TITLE
Langugage defs broken

### ISSUE THREAD

**Issue by klngwll** [libris/kitin#289]
Translation of language defs in hitlist to a friendly label is broken

**Comment by oBlissing** [comment]
Are you talking about the facets?

**Comment by sweco-semhul** [comment]
Facets is returned with a collection of id:s. For language its translated to labels by requesting language definitions witch return zero languages in production http://xl.libris.kb.se/def/_search?q=*+about.@type:Language&n=10000

(Seems to work properly in QA http://labwhelk.libris.kb.se/def/_search?q=*+about.@type:Language&n=10000)

**Comment by niklasl** [comment]
Def-data needed to be re-indexed. Now fixed.
